CREATE TABLE IF NOT EXISTS JSONData (
  Id INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  Body VARCHAR(10299),
  FolderId INT NOT NULL,
  CreatedAt DATETIME NOT NULL,
  PRIMARY KEY (Id));

ALTER TABLE JSONData
  ADD CONSTRAINT JSONData_FolderId_Folder_FK
    FOREIGN KEY (FolderId)
      REFERENCES Folder (Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE;
