CREATE TABLE IF NOT EXISTS UserPassword (
  UserId INT NOT NULL,
  Password VARCHAR(256) NOT NULL,
  PRIMARY KEY (UserId));

ALTER TABLE UserPassword
  ADD CONSTRAINT Password_UserId_FK
FOREIGN KEY (UserId)
REFERENCES User(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
