CREATE TABLE IF NOT EXISTS Folder (
  Id INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  ParentId INT,
  CreatedAt DATETIME NOT NULL,
  UpdatedAt DATETIME,
  PRIMARY KEY (Id));

ALTER TABLE Folder
  ADD CONSTRAINT Folder_ParentId_Folder_FK
    FOREIGN KEY (ParentId)
      REFERENCES Folder(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE;