CREATE TABLE IF NOT EXISTS UserRole (
  UserId INT NOT NULL,
  RoleId INT NOT NULL,
  PRIMARY KEY (UserId, RoleId));

ALTER TABLE UserRole
  ADD CONSTRAINT UserRole_UserId_FK
FOREIGN KEY (UserId)
REFERENCES User(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE UserRole
  ADD CONSTRAINT UserRole_RoleId_FK
FOREIGN KEY (RoleId)
REFERENCES Role(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

